spring:
  application:
    name: warehouse-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mediasoft_db
    username: postgres
    password: 1
#  datasource:
#    url: jdbc:h2:mem:testdb;NON_KEYWORDS=value
#    driver-class-name: org.h2.Driver

server:
  port: 8080
  servlet.context-path: /